window.LumiGame=window.LumiGame||{};
class EndingScreen {
 constructor(game){this.game=game;this.screenEl=document.getElementById('ending-screen');this.isPlayingSequence=false;this.sequenceTimer=0;document.getElementById('btn-restart').onclick=()=>{this.hide();game.menu.show('<h2>Recomeçar a jornada?</h2><p class="menu-copy">O progresso desta jornada será apagado. As configurações serão mantidas.</p><button class="btn-primary" data-action="confirm-restart">Recomeçar</button><button class="btn-secondary" data-action="cancel-restart">Voltar</button>');};game.pendingRestart=()=>game.restartGame();document.getElementById('btn-explore').onclick=()=>{this.hide();game.menu.map();};}
 startSequence(){this.isPlayingSequence=true;this.sequenceTimer=0;this.game.player.vx=0;this.game.input.reset();this.game.camera.setCinematicTarget(this.game.level.ancestralTree.x,270,.04);this.game.sound.playTreeAwakening();document.getElementById('game-hud').hidden=true;}
 update(dt){if(!this.isPlayingSequence)return;this.sequenceTimer+=dt;const g=this.game,t=g.level.ancestralTree;if(this.sequenceTimer>=1.5&&!t.isAwakened){t.isAwakened=true;if(!g.reducedMotion)g.particleSystem.emitStarBurst(t.x,t.y-250,true);}if(this.sequenceTimer>= (g.reducedMotion?2:4)){this.isPlayingSequence=false;this.showCard();}}
 showCard(){const total=this.game.totals();document.getElementById('ending-stat-main').textContent='Fragmentos devolvidos: '+total.main+'/20';document.getElementById('ending-stat-secret').textContent='Memórias encontradas: '+total.secret+'/3';this.screenEl.classList.add('active');this.screenEl.inert=false;document.getElementById('btn-explore').focus();}
 hide(){this.isPlayingSequence=false;this.screenEl.classList.remove('active');this.screenEl.inert=true;}
}
window.LumiGame.EndingScreen=EndingScreen;
