window.LumiGame=window.LumiGame||{};
class JourneyMenu {
 constructor(game){
  this.game=game;this.el=document.getElementById('journey-menu');this.card=document.getElementById('journey-card');this.action=null;
  document.getElementById('btn-pause').onclick=()=>this.pause();
  this.el.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)this.act(b.dataset.action);});
  window.addEventListener('keydown',e=>{if(e.code==='Escape'){e.preventDefault();if(game.settingsModal.isOpen){game.settingsModal.close();return;}if(game.state==='playing')this.pause();else if(game.state==='paused')this.resume();}if(e.code==='Tab')this.trap(e);});
  this.home();
 }
 trap(e){const parent=this.game.settingsModal.isOpen?document.getElementById('settings-modal'):this.el.hidden?document.getElementById('ending-screen'):this.el;if(parent.hidden||(!this.game.settingsModal.isOpen&&this.el.hidden&&this.game.state!=='ending'))return;const controls=[...parent.querySelectorAll('button:not(:disabled),input')];if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}
 show(html,state='menu'){this.game.state=state;this.game.input.reset();this.el.hidden=false;this.card.innerHTML=html;document.getElementById('game-hud').hidden=true;this.card.querySelector('button:not(:disabled)')?.focus();}
 hide(){this.el.hidden=true;document.getElementById('game-hud').hidden=false;document.activeElement?.blur();this.game.input.reset();this.game.canvas.focus();}
 home(){
  const g=this.game,has=Object.keys(g.save.levels).length>0;const totals=g.totals();
  this.show('<span class="eyebrow">UMA JORNADA DE LUZ E MEMÓRIA</span><h1 class="nara-title">Nara<span>O Despertar da Floresta</span></h1><p class="menu-copy">O céu perdeu suas estrelas.<br>Uma pequena guardiã ainda se lembra do caminho.</p><div class="menu-buttons"><button class="btn-primary" data-action="continue">'+(has?'Continuar jornada':'Começar jornada')+'</button><button class="btn-secondary" data-action="map">Capítulos</button><button class="text-button" data-action="settings">Configurações</button>'+(has?'<button class="text-button" data-action="restart-prompt">Nova jornada</button>':'')+'</div><p class="menu-foot">5 capítulos · '+totals.main+'/20 fragmentos · '+totals.secret+'/3 memórias</p>'+(g.storageUnavailable?'<p>O navegador não permitiu salvar. Mantenha esta aba aberta para preservar a jornada.</p>':''));
 }
 map(){const g=this.game;this.show('<span class="eyebrow">O CAMINHO DA GUARDIÃ</span><h2>Uma floresta, cinco memórias</h2><div class="chapter-list">'+LumiGame.LevelData.chapters.map((c,i)=>'<button class="chapter-row" data-action="level-'+i+'" '+(i>g.save.unlocked?'disabled':'')+'><span class="chapter-number">'+(g.save.completed.includes(i)?'✓':i+1)+'</span><span><small>'+c.subtitle+'</small><strong>'+c.name+'</strong></span><span>'+(i>g.save.unlocked?'◇':'→')+'</span></button>').join('')+'</div><button class="btn-secondary" data-action="home">Voltar ao menu</button>');}
 intro(index){this.game.loadLevel(index);this.game.persist();const c=this.game.level.chapter;this.show('<span class="eyebrow">'+c.subtitle+'</span><h2>'+c.name+'</h2><p class="menu-copy">'+c.story+'</p><div class="control-note">'+c.lesson+'</div><button class="btn-primary" data-action="play">Entrar na floresta →</button>','intro');}
 chapterComplete(){const c=this.game.level.chapter;this.show('<span class="eyebrow">CAPÍTULO RESTAURADO · '+(this.game.level.index+1)+'/5</span><div class="chapter-seal">✧</div><h2>'+c.name+'</h2><p class="menu-copy">'+c.end+'</p><div class="menu-buttons"><button class="btn-primary" data-action="next">Seguir a luz →</button><button class="text-button" data-action="home">Voltar ao menu</button></div>','chapter-complete');}
 pause(){if(this.game.state!=='playing')return;this.game.persist();this.show('<span class="eyebrow">A FLORESTA PODE ESPERAR</span><h2>Uma pausa no caminho</h2><p class="menu-copy">'+this.game.level.chapter.name+'</p><div class="menu-buttons"><button class="btn-primary" data-action="resume">Continuar</button><button class="btn-secondary" data-action="settings">Configurações</button><button class="text-button" data-action="controls">Controles</button><button class="text-button" data-action="map">Capítulos</button><button class="text-button" data-action="home">Menu principal</button></div>','paused');}
 resume(){this.game.state='playing';this.hide();}
 act(action){const g=this.game;if(action.startsWith('level-')){const i=Number(action.slice(6));if(Number.isInteger(i)&&i>=0&&i<=g.save.unlocked)this.intro(i);return;}
  switch(action){case 'restart-prompt':this.show('<h2>Uma nova jornada?</h2><p class="menu-copy">O progresso salvo será apagado. As configurações serão mantidas.</p><button class="btn-primary" data-action="confirm-restart">Recomeçar</button><button class="btn-secondary" data-action="home">Cancelar</button>');break;case 'confirm-restart':g.restartGame();break;case 'cancel-restart':g.state='ending';this.el.hidden=true;g.endingScreen.showCard();break;case 'continue':this.intro(g.save.current);break;case 'play':case 'resume':this.resume();break;case 'home':g.persist();this.home();break;case 'map':this.map();break;case 'next':this.intro(Math.min(4,g.level.index+1));break;case 'settings':g.settingsModal.open();break;case 'controls':this.show('<h2>Controles da jornada</h2><p class="menu-copy">A/D ou ←/→ para mover. Espaço, W ou ↑ para pular; segure para um salto alto. S/↓ + pulo desce de galhos. F/J lança um ataque de luz que purifica criaturas e reflete projéteis. Três corações representam sua vida; santuários restauram a vida. Esc pausa. No celular, use ◀ ▶, ✧ e ▲; deslize o dedo para baixo no botão ▲ para descer.</p><p class="control-note">Reúna quatro estrelas douradas e siga o arco aceso. As violetas são opcionais. Uma queda retorna ao santuário sem perder estrelas.</p><button class="btn-primary" data-action="resume">Continuar</button>','paused');break;}
 }
}
window.LumiGame.JourneyMenu=JourneyMenu;
